// <auto-generated />
namespace SSW.DataOnion.UserGroupDemo.VanillaEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InheritanceExample : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InheritanceExample));
        
        string IMigrationMetadata.Id
        {
            get { return "201506130950329_InheritanceExample"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
